icons_format = "{icon}"

[theme]
theme = "slick"

[theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#ffffff"
#separator = ""

[icons]
icons = "material-nf"

[[block]]
block = "custom"
command = "sed 's/  //' <(curl 'https://wttr.in/?format=2' -s)  "
interval = 600

[[block]]
block = "battery"
interval = 20
format = "  $icon $percentage ($time)  "
charging_format = " $icon $percentage ($power) "

[[block]]
block = "cpu"
interval = 10
format = "  $icon $utilization @ $frequency.eng(w:4)  "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 60
warning = 20.0
alert = 10.0
format = "  $icon root: $used.eng(w:4) / $total  "

[[block]]
block = "memory"
format = "  $icon $mem_used.eng(w:4) / $mem_total.eng(w:3)  "
interval = 20

[[block]]
block = "sound"
format = "  $icon $volume  "
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
interval = 20
format = "  󰩠 {$signal_strength $ssid @$frequency|Wired connection} via $device  "

[[block]]
block = "time"
interval = 50
format = "  $icon $timestamp.datetime(f:'%a %m/%d %I:%M %p')  "
